// Auto-generated by @tradercore/migration-engine — do not edit manually.
// Re-generate with: bun run db:generate
import type { PluginMigration } from '@tradercore/migration-engine';

export const migrations: PluginMigration[] = [
    {
        version: '0000',
        sql: `
CREATE TABLE IF NOT EXISTS plugins (
    name TEXT PRIMARY KEY,
    version TEXT NOT NULL,
    location TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
`,
    },
];
