// Auto-generated by @tradercore/migration-engine — do not edit manually.
// Re-generate with: bun run db:generate
import type { PluginMigration } from '@tradercore/migration-engine';

export const migrations: PluginMigration[] = [
    {
        version: '0000',
        sql: `CREATE TABLE "test_plugin_entries" (
	"id" text PRIMARY KEY NOT NULL,
	"message" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
`,
    },
];
